name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hacs:
    runs-on: ubuntu-latest
    name: runner / hacs
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Run HACS validation
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a # 22.5.0
        with:
          category: integration

  hassfest:
    runs-on: ubuntu-latest
    name: runner / hassfest
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@master

  check-markdown:
    runs-on: ubuntu-latest
    name: runner / markdownlint
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Run Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23
        with:
          globs: "**/*.md"

  check-links:
    name: runner / linkspector
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@963b6264d7de32c904942a70b488d3407453049e # v1
        with:
          fail_on_error: false
          reporter: github-pr-review

  lint:
    runs-on: ubuntu-latest
    name: runner / lint
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          dev-dependencies: true

      - name: Lint with flake8
        run: task lint

      - name: Type check with mypy
        run: task type-check

  test:
    runs-on: ubuntu-latest
    name: runner / test
    needs: [check-markdown, check-links, lint, hacs, hassfest]
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          dev-dependencies: true

      - name: Run tests with pytest
        run: task test

      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        with:
          filename: coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
